chat_app/urls.py
from django.urls import path

from chat_app import views

app_name = 'chat_app'
urlpatterns = [
    # Handles route to '/', home/index page
    # 'register/', register page
    # 'login/', login page
    # 'logout/' logout
    path('', views.ChatFormView.as_view(), name='index'),
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.signout, name='logout')
]

hello_chat_server/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from chat_app import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]

chat_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Chat(models.Model):
    """contains models for user, message and date to stored in database"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=250,
                               default="Type and text like 'Hello'  ")
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username + "  " + str(self.date)

chat_app/forms.py
from django import forms
from django.contrib.auth.models import User

from chat_app.models import Chat


class ChatForm(forms.ModelForm):
    """Provides form for Chat model"""

    class Meta:
        model = Chat
        # fields = '__all__'
        exclude = ['user', 'date']


class LoginForm(forms.Form):
    """Provides form for User model"""

    username = forms.CharField(label='username')
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(forms.ModelForm):
    """Provides form for User model"""
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='confirm_password',
                                       widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'confirm_password']

chat_app/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

from chat_app.forms import ChatForm, LoginForm, RegisterForm
from chat_app.models import Chat


class ChatFormView(View):
    """Uses the ChatForm created in forms.py and handles 'GET' 'POST' requests
    from index.html """
    form_class = ChatForm
    template_name = 'index.html'

    # sends query and form on request
    def get(self, request):
        form = self.form_class(None)
        chats = Chat.objects.all().order_by('-date')
        # vector = SearchVector('message', weight='A')
        # vector_venture = SearchVector('title', weight='B') + SearchVector('description', weight='C')
        # query = SearchQuery('innovation')
        # print( Chat.objects.annotate(search=SearchVector('message')
        # ).filter(search__icontains=query))
        # Chat.objects.extra()
        # to_tsvector(COALESCE(school, '')) @@ (plainto_tsquery('alamo')) = true;
        # where=["to_tsvector('english', coalesce(school, '')) @@ (plainto_tsquery(%s)) = true"]

        ####################################################
        #   final query

        result = Chat.objects.extra(where=["to_tsvector(coalesce(message, '')) @@ (to_tsquery('inn:*')) = true"]).values('message')
        print(result)
        ####################################################
        return render(request, self.template_name,
                      {'form': form, 'chats': chats})

    # stores data to database on request
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = self.request.user
            post.save()
            chats = Chat.objects.all().order_by('-date')
            return render(request, self.template_name,
                          {'form': form, 'chats': chats})
        else:
            return render(request, self.template_name, {'form': form})


class LoginFormView(View):
    """Uses the LoginForm created in forms.py and handles 'GET' 'POST' requests
        from form_register.html """
    form_class = LoginForm
    template_name = 'form_login.html'

    # sends query and form on request
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name,
                      {'form': form})

    # authenticates user request
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                messages.success(request, "Logged in Successfully")
                return redirect('/')
            else:
                messages.error(request, "Incorrect Credentials")
                return redirect('chat_app:login')
        else:
            messages.error(request, "Incorrect credentials")
            return render(request, self.template_name, {'form': form})


class RegisterFormView(View):
    """Uses the RegisterForm created in forms.py and handles 'GET' 'POST' requests
        from form_register.html """
    form_class = RegisterForm
    template_name = 'form_register.html'

    # sends query and form on request
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name,
                      {'form': form})

    # stores data to database on request and authenticates the user
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            user.set_password(password)
            if password == confirm_password:
                user.save()
                messages.success(request, "Registered Successfully")
                user = authenticate(username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('/')
            else:
                messages.error(request, "Incorrect credentials")
                return render(request, self.template_name, {'form': form})
        else:
            messages.error(request, "Incorrect credentials")
            return render(request, self.template_name, {'form': form})


def signout(request):
    """logs out the user on request"""
    logout(request)
    return redirect('chat_app:index')

chat_app/templates/form_login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
    {% if messages %}
        <ul class="messages">
            <!--looping through messages-->
            {% for message in messages %}
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-hidden="true">&times;
                    </button>
                    {{ message }}
                </div>
                {# <li{% if message.tags %}#}
                {# class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container">
        <div class="row">
            <h2 style="text-align: center;">Login</h2>
            <hr>
            <br>
            <div class="col-md-2"></div>
            <div class="col-md-8  col-sm-12">

                <!-- Displaying Form -->
                <div>
                    {% for field in form %}
                        <form class="form-horizontal" action="" method="post"
                              enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="text-danger small">{{ field.errors }}</div>
                            </div>
                            <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                            <div class="col-sm-10">{{ field }}</div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Displaying Form -->
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

chat_app/templates/form_register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
    {% if messages %}
        <ul class="messages">
            <!--looping through messages-->
            {% for message in messages %}
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-hidden="true">&times;
                    </button>
                    {{ message }}
                </div>
                {#                <li{% if message.tags %}#}
                {#                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container">
        <div class="row">
            <h2 style="text-align: center;">Register</h2>
            <hr>
            <br>

            <div class="col-md-2"></div>
            <div class="col-md-8 col-sm-offset-1 col-sm-12">
                <!-- Displaying Form -->
                {% for field in form %}
                    <form class="form-horizontal" action="" method="post"
                          enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="text-danger small">{{ field.errors }}</div>
                        </div>
                        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                        <div class="col-sm-10">{{ field }}</div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit
                        </button>
                    </div>
                </div>
                <!-- Displaying Form -->
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

chat_app/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    {% if messages %}
        <ul class="messages">
            <!--looping through messages-->
            {% for message in messages %}
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-hidden="true">&times;
                    </button>
                    {{ message }}
                </div>
                {# <li{% if message.tags %}#}
                {# class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% if request.user.username == '' %}
                    <a href="{% url 'chat_app:login' %}">Login</a>
                    <a href="{% url 'chat_app:register' %}">Register</a>
                {% else %}
                    <a href="#">{{ request.user }}</a>
                    &nbsp;
                    <a href="{% url 'chat_app:logout' %}">Logout</a>
                {% endif %}
                <div class="chat-box-parent">
                    <div class="chat-box">
                        <ul>
                            {% for chat in chats %}
                                <li><h3>{{ chat.user.username }}<span
                                        style="float: right;font-size: 12px;">{{ chat.date.date }}</span>
                                </h3></li>
                                <li style="float: right; font-size: 10px;">{{ chat.date.time }}</li>
                                <li>{{ chat.message }}</li>
                                <hr>
                            {% endfor %}
                        </ul>
                    </div>
                    <form class="form-horizontle" action="" method="post">
                        {% for field in form %}

                            {% csrf_token %}
                            <div class="form-group">
                                <div class="text">{{ field.errors }}</div>
                                {#                        <label class="text">{{ field.label }}</label>#}
                                <div>{{ field }}</div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success">Submit
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>

    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>